version: '3'
services:
  hinemos-manager:
    image: 'hinemos/hinemos-5.0-jp'
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
      - '5514:514'
      - '80:80'
      - '1616:161/udp'
      - '1626:162/udp'
    privileged: true
    command: /sbin/init